apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: knamgay-deploy
  name: sandeep-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knamgay-deploy
  template:
    metadata:
      labels:
        app: knamgay-deploy
    spec:
      containers:
      - image: Kuenzang-Namgay7/takin:latest
        name: pet
